# Generated by Django 5.0.3 on 2024-03-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_mecanico'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geral.oficina', verbose_name='Oficina'),
        ),
    ]
